### PR TITLE
Redemption issues article docs

### PR DESCRIPTION
**Pull request by Aduralere54256703**

### CODE REVIEW

**Review by thetallralph — COMMENTED** [review]
> On occasion, especially when using external payment gateways like PayPal, an order might be
> marked as validated in your system, even though the payment did not successfully process.
> Under such circumstances, the points are only reinstated to the customer's account if the
> retailer takes action to cancel the order.

@Aduralere54256703 This issue was there long ago, ask in the bug channel if it is still exist.

**Comment by Aduralere54256703** [comment]
I have confirmed, It still exists.

**Comment by thetallralph** [comment]
I decomposed the section for it to be better structured.

We will move the issue on about paypal payment on woocommerce to the Woocommerce article: 

> 
> On occasion, especially when using external payment gateways like PayPal, an order might be
> marked as validated in your system, even though the payment did not successfully process.
> Under such circumstances, the points are only reinstated to the customer's account if the
> retailer takes action to cancel the order.

Concerning the issue on the redemption process, I tranformed it in a FAQ question.

**Review by thetallralph — APPROVED** [review]
This can be merged.

**Pull request merged**
