### PR TITLE
Feature/integrations bigcommerce redemption

### PR DESCRIPTION
**Pull request by Aduralere54256703**

### CODE REVIEW

**Review by thetallralph — APPROVED** [review]
I have reviewed this and made some change to the doc hierarchy and also improve readability and consistency for the different section.

@Aduralere54256703 You need to be sure that you have tested the feature you are documented well. For example you were still using the naming Non Eligible Collection when actually in the app it was "Collections exclusion - Loyalty".

Other than that it is important to keep a similar writing structure from a section to another. We will eventually talk about it during a meeting if I have time.

I will approve this PR.

**Comment by thetallralph** [comment]
@dlionel This PR is ready for review.

**Comment by Aduralere54256703** [comment]
Ok sir
I've made a note of all the corrections.
I look forward to the meeting sir.

**Review by thetallralph — DISMISSED** [review]

**Comment by thetallralph** [comment]
@Aduralere54256703 tHERE I

**Review by thetallralph — APPROVED** [review]

**Review by thetallralph — APPROVED** [review]

**Comment by Aduralere54256703** [comment]
@thetallralph 
There's a Prettier issue with this merge, sir, which has prevented me from making changes on other branches when rebasing from the main branch.
Should I create a fix PR to resolve the issue?

**Comment by thetallralph** [comment]
Yes you can create the fix for it.

**Pull request merged**
