### PR TITLE
Big-commerce article docs

### PR DESCRIPTION
**Pull request by Aduralere54256703**

### CODE REVIEW

**Comment by thetallralph** [comment]
I have multiple conflict while trying to pull this branch into my local repo. @Aduralere54256703 Make sure the branch is up to date with Main before submitting for request.

**Comment by thetallralph** [comment]
@Aduralere54256703 Is the issue with conflict solved ?

**Comment by Aduralere54256703** [comment]
Yes.
I'm able to pull and push from my end here.

**Review by thetallralph — COMMENTED** [review]
@Aduralere54256703 I am done reviewing the doc and made a few change. Pay attention to these for future doc:  
**Be Specific and Complete**:  You only mentioned API key but actually merchants need to provide Client ID, Client secret, Access token, and Store URL.

**Use Clear Structure**: Break down complex steps into sub-steps (like the API credential generation process)
**Use direct language**: Use "you" instead of "merchants".

**Review by thetallralph — APPROVED** [review]

**Pull request merged**
