### PR TITLE
Feature/integrations beansemail replacement tag

### PR DESCRIPTION
**Pull request by Aduralere54256703**

### CODE REVIEW

**Comment by Aduralere54256703** [comment]
Updated Replacement Tags

The following replacement tags are no longer supported in BeansEmail:

- [%last_name%]
- [%referral_link%]
- [%referral_reward_short%]
- [%liana_transaction_type%]
- [%liana_transaction_points%]
- [%liana_points_value%]
- [%liana_points_balance%]
- [%liana_transaction_description%]
- [%liana_transaction_sign%]

Currently Supported Tags
The replacement tags now available in BeansEmail are:

- [%first_name%]
- [%beans_value%]
- [%beans_balance%]
- [%transaction_description%]
- [%transaction_delta%]
- [%transaction_delta%]
- [%referrer_name%]
- [%referral_reward%]
- [%unsubscribe_link%]

**Review by thetallralph — CHANGES_REQUESTED** [review]
- Beans Emails is not spelled correctly.
- You are talking about Replacement Tags but also tallking about Merges tags. Which is quite confusing.
-

**Review by thetallralph — CHANGES_REQUESTED** [review]
@Aduralere54256703 
I have reviewed the doc and made some changed.

The section has been made light by removing Notification specific tags. they will be presented while describing the Notification in the Notification section.

Other than that concerning Global tags, i think there is more than the one you shared. try to contact Dafia to be sure that you have a more exhaustive list.

**Comment by Aduralere54256703** [comment]
@thetallralph 
I have reached out to Dafia but he has no information About more global tags.

**Comment by Aduralere54256703** [comment]
@thetallralph 
I have been updated on the replacement tags.
Here Is the available tags:
### General tags
# first_name: The first name of the shopper.
# last_name: The last name of the shopper.
# unsubscribe_link: The link of the unsubscribe button.
# beans_balance: The shopper's points balance.
# beans_value: The value of the shopper's points balance.

### If tier is activated
# tier_name: The name of the shopper's tier.

### For points transactions: debit or credit
# transaction_delta: The delta (amount of points) of the current transaction.
# transaction_description: The description of the current transaction.

### Only for referral invitations
# referral_reward: The reward (amount of points) of the referral invitation.
# referrer_name: The name of the referrer sending the invitation.
# referral_link: The link of the referral invitation.

I would like to confirm if I can make the update to change "global tags" to "general tags"?

**Pull request closed without merging**
